// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "426f496b-f13d-44af-b94a-58f755a31fb0";

const char SSID[]               = "KOPILAINHATI";    // Network SSID (name)
const char PASS[]               = "Eskopipakmuh";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "77gY8UY7Lde3mJak7zTKs!WZs";    // Secret device password


CloudTemperatureSensor temperature;
int soilMoisture;
CloudRelativeHumidity kelembapan;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(soilMoisture, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(kelembapan, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);